---
name: Set Up Google Container Structure Test
description: This action installs Google's Container Structure Test tool.

inputs:
  version:
    description: The version of Container Structure Test to install.
    required: false
    default: "1.16.0"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [[ "$(uname -m)" == "x86_64" ]]; then
          export architecture="amd64"
        elif [[ "$(uname -m)" == "aarch64" ]]; then
          export architecture="arm64"
        else
          echo "Unsupported architecture: $(uname -m)"
          exit 1
        fi

        if [[ "${{ inputs.version }}" == "latest" ]]; then
          export version="$(curl --silent https://api.github.com/repos/GoogleContainerTools/container-structure-test/releases/latest | jq -r '.tag_name')"
        else
          export version="${{ inputs.version }}"
        fi

        mkdir --parents "${HOME}/.google-container-structure-test"

        curl --location --silent --show-error --fail "https://storage.googleapis.com/container-structure-test/v${version}/container-structure-test-linux-${architecture}" \
          --output "${HOME}/.google-container-structure-test/container-structure-test"

        chmod +x "${HOME}/.google-container-structure-test/container-structure-test"

        echo "${HOME}/.google-container-structure-test" >>"${GITHUB_PATH}"

        ## DEBUG
        ls -lrt "${HOME}/.google-container-structure-test"
        echo "${PATH}"
        "${HOME}/.google-container-structure-test/container-structure-test" version

        # container-structure-test version
