---
name: Set Up Google Container Structure Test
description: This action installs Google's Container Structure Test tool.

inputs:
  version:
    description: The version of Container Structure Test to install.
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Set Up Google Container Structure Test
      run: |
        if [[ "$(uname -m)" == "x86_64" ]]; then
          architecture="amd64"
        elif [[ "$(uname -m)" == "aarch64" ]]; then
          architecture="arm64"
        else
          echo "Unsupported architecture: $(uname -m)"
          exit 1
        fi

        if [[ "${{ inputs.version }}" == "latest"]]; then
          version="$(curl --silent https://api.github.com/repos/GoogleContainerTools/container-structure-test/releases/latest | jq -r '.tag_name')"
        else
          version="${{ inputs.version }}"
        fi

        mkdir --parents "${{ github.workspace }}/.google-container-structure-test"

        curl --location --silent --show-error --fail --output "${{ github.workspace }}/.google-container-structure-test/container-structure-test" "https://storage.googleapis.com/container-structure-test/v${version}/container-structure-test-linux-${architecture}"

        chmod +x "${{ github.workspace }}/.google-container-structure-test/container-structure-test"

        echo "${{ github.workspace }}/.google-container-structure-test" >>"${{ GITHUB_PATH }}"

        container-structure-test version
