---
name: Dependency Review

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  dependency-review:
    name: Dependency Review
    permissions:
      contents: read
      pull-requests: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/dependency-review.yml@e22f0c9cafa7528d5594c19fe1401ec893424272 # v4.0.4
