---
name: OpenSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 6 * * 1"

permissions: {}

jobs:
  openssf-scorecard:
    name: OpenSSF Scorecard
    permissions:
      contents: read
      id-token: write
      security-events: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/openssf-scorecard.yml@5d8d0f00346daa26a7dd1283ecd098bbcd2b5396 # v4.1.1
