---
name: OpenSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 6 * * 1"

permissions: {}

jobs:
  openssf-scorecard:
    name: OpenSSF Scorecard
    permissions:
      contents: read
      id-token: write
      security-events: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/openssf-scorecard.yml@92832dad5ea35a24fa25db98a932020e03a300ce # v4.0.2
