---
name: Super Linter

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/super-linter.yml@92832dad5ea35a24fa25db98a932020e03a300ce # v4.0.2
    with:
      super-linter-variables: |
        {
          "VALIDATE_JSCPD": false
        }
