---
name: Super Linter

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/super-linter.yml@1bceb37c920feafe4d6fc6e3c57b3ce5bd1146e6 # v4.0.3
    with:
      super-linter-variables: |
        {
          "VALIDATE_JSCPD": false
        }
