---
name: Super Linter

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/super-linter.yml@897b3baca10a174d67953e47b93339ff3680fc24 # v3.6.1
    with:
      super-linter-variables: |
        {
          "VALIDATE_JSCPD": false
        }
