---
name: Zizmor

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  zizmor:
    name: Zizmor
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/zizmor.yml@92832dad5ea35a24fa25db98a932020e03a300ce # v4.0.2
